### ISSUE TITLE
Not working on Android 6.0 , crashing (libavcodec.so: has text relocations)

### ISSUE THREAD

**Issue by branemk** [wseemann/FFmpegMediaPlayer#64]
I am testing my app on android 6.0 and I am getting error libavcodec.so: has text relocations. I searched Google and seems like this is FFmpeg library problem. Hopefully is going to be fixed and this library is going to be updated, or maybe you can tell us a workaround .

I don't use NDK,but this might help the developer http://slowbutdeadly.blogspot.mk/2015/09/javalangunsatisfiedlinkerror-dlopen.html .

Here is log

10-03 10:52:40.434 4867-4867/com.example.brane.radio E/AndroidRuntime: FATAL EXCEPTION: main
10-03 10:52:40.434 4867-4867/com.example.brane.radio E/AndroidRuntime: Process: com.example.brane.radio, PID: 4867
10-03 10:52:40.434 4867-4867/com.example.brane.radio E/AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.example.brane.radio-1/lib/x86/libavcodec.so: has text relocations
10-03 10:52:40.434 4867-4867/com.example.brane.radio E/AndroidRuntime:     at java.lang.Runtime.loadLibrary(Runtime.java:372)
10-03 10:52:40.434 4867-4867/com.example.brane.radio E/AndroidRuntime:     at java.lang.System.loadLibrary(System.java:1076)
10-03 10:52:40.434 4867-4867/com.example.brane.radio E/AndroidRuntime:     at wseemann.media.FFmpegMediaPlayer.<clinit>(FFmpegMediaPlayer.java:620)
10-03 10:52:40.434 4867-4867/com.example.brane.radio E/AndroidRuntime:     at com.example.brane.radio.MusicService.play(MusicService.java:121)
10-03 10:52:40.434 4867-4867/com.example.brane.radio E/AndroidRuntime:     at com.example.brane.radio.MusicService.onStartCommand(MusicService.java:84)
10-03 10:52:40.434 4867-4867/com.example.brane.radio E/AndroidRuntime:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
10-03 10:52:40.434 4867-4867/com.example.brane.radio E/AndroidRuntime:     at android.app.ActivityThread.-wrap17(ActivityThread.java)
10-03 10:52:40.434 4867-4867/com.example.brane.radio E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
10-03 10:52:40.434 4867-4867/com.example.brane.radio E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-03 10:52:40.434 4867-4867/com.example.brane.radio E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)
10-03 10:52:40.434 4867-4867/com.example.brane.radio E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5417)
10-03 10:52:40.434 4867-4867/com.example.brane.radio E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
10-03 10:52:40.434 4867-4867/com.example.brane.radio E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-03 10:52:40.434 4867-4867/com.example.brane.radio E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by krazykira** [comment]
I am facing the same problem. Also the song being played gets skips sometime randomly

**Comment by adelinolobao** [comment]
I'm also facing this issue, did you guys manage to solve it?

**Comment by pfaffenrodt** [comment]
Temp workaround using "22" and not "23" as targetSDKVersion.


source:
http://stackoverflow.com/questions/32346402/libavcodec-so-has-text-relocations

According to AReallyGoodName this commits are related 
https://github.com/FFmpeg/FFmpeg/commit/f963f80399deb1a2b44c1bac3af7123e8a0c9e46
https://github.com/FFmpeg/FFmpeg/commit/cb416a7d795414aaa534c27943bda0d3aef3b5a1

**Comment by adelinolobao** [comment]
Thank you for the answer, I know that workaround but I was searching for a permanent solution. I think I will downgrade my application until a more stable fix.

**Comment by alexeyvasilyev** [comment]
I have created a bug report for ffmpeg team. Looks like they are not going to fix that.
https://trac.ffmpeg.org/ticket/4928

**Comment by adelinolobao** [comment]
Hi guys,
If you look the commit change in google source code change you can see the problem
https://android-review.googlesource.com/#/c/155950/1/linker/linker.cpp

It looks like they forgot to remove the if :| WTF

**Comment by alexeyvasilyev** [comment]
Created a bug report in Android BTS
https://code.google.com/p/android/issues/detail?id=191235

Vote for that!

**Comment by pfaffenrodt** [comment]
@alexeyvasilyev Could you add the link, what they are requesting. at ticket https://code.google.com/p/android/issues/detail?id=191235

**Comment by alexeyvasilyev** [comment]
Publicly shared link to reproduce the issue on x86 device (e.g. emulator)
https://drive.google.com/open?id=0B7ZLDetY9bcOQVVLUmI0MlliZkk

**Comment by adelinolobao** [comment]
So, from what I understood from the last comment
https://code.google.com/p/android/issues/detail?id=191235

Google will not change anything, so the only change that we have this running again on Android M is to ask FFMpeg to change their implementation right? I add a quick lookand a bunch of apps in the store are using ffmpeg as their player so I'm guessing that they are having problems too.

What you guys are plannign to do? For now I revert my app, but I want to target SDK 23 in order to use the newest support libraries.

**Comment by branemk** [comment]
Guys, this is not bug in Marshmallow, FFmpeg library need to be patched . And when FFMpeg is patched then FFmpegMediaPlayer probably can be updated. 

If you see in previous versions there is a warning in log saying:

"libfoo.so has text relocations. This is wasting memory and prevents security hardening. Please fix.".

But os will load the library anyway .

Some lib dev fixed this with recompiling shared object with the latest NDK. I leaved link when I posted this issue to page where this is explained. 

I don't know if developer of FFmpegMediaPlayer tried to recompile the library with latest NDK . This is the link http://slowbutdeadly.blogspot.mk/2015/09/javalangunsatisfiedlinkerror-dlopen.html . I never used NDK in my live.

**Comment by alexeyvasilyev** [comment]
I do not use FFmpegMediaPlayer which looks like is based on a quite outdated ffmpeg version 2.5.3.

I'm using ffmpeg 2.8.1 and it does not have text rellocation issue on armv7, armv7-a, x86_64 build. However I do have the issue on x86 build. I will try to revert some x86 specific commits in ffmpeg mentioned in https://trac.ffmpeg.org/ticket/4928

**Comment by adelinolobao** [comment]
If you manage to put ffmpeg working without text rellocation issue share it. I manage to update the internal version of ffmpeg from FFmpegMediaPlayer and compile it using ndk10e but text relocations appear (as expected) but with your custom build maybe we can manage to solve it

**Comment by atul14** [comment]
Hi, anybody managed to solve this? If yes, need help.

**Comment by wseemann** [comment]
Yes, is can be fixed by compiling FFmpeg with the --disable-asm flag set.

**Comment by atul14** [comment]
Can you kindly help with the steps please.

**Comment by AlvaroMolano** [comment]
@wseemann will you upload those compiled libs?
Please

**Comment by raeve92** [comment]
News about Android 6.0?

**Comment by mymvercher** [comment]
+1

**Comment by vanwafang** [comment]
Hello all.

Well I just got it running compiling the libs on my own.
Never did anything with Android NDK before and it took me 18+ hours to
finally come to success.
Yesterday @11 pm the adventure started.

Here are some of my steps:
- Installed Fedora 23 (64-bit) <--- does not work with 32-bit
- Installed Android NDK
- Installed Android SDK
- Installed Android SDK Build Tools
- Installed Maven Support Repository
- ...

Since the projects build task is not based on ant anymore I had to start the build process with this command:
./gradlew assembleDebug

Added this:
FLAGS="$FLAGS --disable-asm"
to arm-build.sh,  mips-build.sh and x86-build.sh

Got this error during build:
common.h:30:2: error: #error missing -D__STDC_CONSTANT_MACROS / #define __STDC_CONSTANT_MACROS
 #error missing -D__STDC_CONSTANT_MACROS / #define __STDC_CONSTANT_MACROS

and this one too:
common.h:183:47: error: 'UINT64_C' was not declared in this scope
     if ((a+0x80000000u) & ~UINT64_C(0xFFFFFFFF)) return (int32_t)((a>>63) ^ 0x7FFFFFFF);

After reading this ...
http://ffmpeg-devel.ffmpeg.narkive.com/Kg4bzsNt/uint64-c-definition
https://github.com/ffms/ffms2/issues/11

... changed this in every ./FFmpegMediaPlayer/gradle/fmp-library/library/src/main/jni/ffmpeg/ffmpeg/[architecture]/include/libavutil/common.h file

#if defined(__cplusplus) && !defined(__STDC_CONSTANT_MACROS)
#define __STDC_CONSTANT_MACROS
#endif

#ifndef INT64_C
#define INT64_C(c) (c ## LL)
#define UINT64_C(c) (c ## ULL)
#endif

Compile generated ".so" files like this libavcodec.so.56. Not good. So ...
After reading this...
http://www.roman10.net/2013/08/18/how-to-build-ffmpeg-with-ndk-r9/

.. changed this in configure file in ffmpeg
LIB_INSTALL_EXTRA_CMD='$$(RANLIB) "$(LIBDIR)/$(LIBNAME)"'
SLIBNAME_WITH_MAJOR='$(SLIBNAME)'
SLIB_INSTALL_NAME='$(SLIBNAME)'
SLIB_INSTALL_LINKS='$(SLIBNAME).ln'

Important thing is that SLIB_INSTALL_NAME is without version information in filename!
with SLIBNAME='$(SLIBPREF)$(FULLNAME)$(SLIBSUF)'
and SLIBPREF="lib"
and SLIBSUF=".so"

So Build output changed from ...
LD	libavutil/libavutil-54.so
LD	libswresample/libswresample-1.so
LD	libavcodec/libavcodec-56.so
LD	libavformat/libavformat-56.so
LD	libswscale/libswscale-3.so

... to
LD	libavutil/libavutil.so
LD	libswresample/libswresample.so
LD	libavcodec/libavcodec.so
LD	libavformat/libavformat.so
LD	libswscale/libswscale.so

good!


Finally got this:
[chris@linux libs]$ tree
.
├── armeabi
│   ├── libavcodec.so
│   ├── libavformat.so
│   ├── libavutil.so
│   ├── libffmpeg_mediaplayer_jni.so
│   ├── libswresample.so
│   └── libswscale.so
├── armeabi-v7a
│   ├── libavcodec.so
│   ├── libavformat.so
│   ├── libavutil.so
│   ├── libffmpeg_mediaplayer_jni.so
│   ├── libswresample.so
│   └── libswscale.so
├── mips
│   ├── libavcodec.so
│   ├── libavformat.so
│   ├── libavutil.so
│   ├── libffmpeg_mediaplayer_jni.so
│   ├── libswresample.so
│   └── libswscale.so
└── x86
    ├── libavcodec.so
    ├── libavformat.so
    ├── libavutil.so
    ├── libffmpeg_mediaplayer_jni.so
    ├── libswresample.so
    └── libswscale.so

I successfully tested them on 2 real devices both armeabi-v7a devices with Android 5.1.1 and Android 4.4.4 and one virtual device under Android 6 with x86 architecture. No crashing anymore

And here are the precompiled binaries :)
https://drive.google.com/file/d/0ByrCnXp4EZ2ydnd3ZnRBc3podkk/view?usp=sharing

**Comment by droidster** [comment]
Hey @vanwafang Thanks for the detailed steps. I've tried and failed many times trying to compile using ndk. Used your precompiled binaries in my app which uses libavcodec.so but for a different purpose, not ffmpeg related. Getting this exception on System.loadLibrary:

`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_buffer_default_free" referenced by "libavcodec.so"...`

Would you know how to fix it.

**Comment by vanwafang** [comment]
Hello @droidster I am not deep enough in C/C++ proramming but I think it's not possible to use the precompiled libs other than for within this project. I guess the error means that there is no function with name "av_buffer_default_free" defined in libavcodec.so. You need another version of this library for your project. But I cannot say which one.

**Comment by asakaplan** [comment]
@vanwafang Thank you very much for the .so files, it's been a headache trying to compile them. I had a working project, and merely replacing the libavutil.so files with the ones from your drive gave the error:

`com.babyplus E/art: dlopen("/data/app/app.name-here/lib/arm/libjniavutil.so", RTLD_LAZY) failed: dlopen failed: library "libavutil.so" not found`

Anyone have any ideas?

**Comment by vanwafang** [comment]
@asakaplan Have you previously been successfully using the precompiled libs provided by this  FFmpegMediaPlayer project?

**Comment by asakaplan** [comment]
@vanwafang I have indeed. I am doing a direct swap of the files, and swapping the files causes the error. Also, I notice they are significantly smaller than the originals, is that expected?

**Comment by vanwafang** [comment]
@asakaplan Where does libjniavutil.so come from?

**Comment by asakaplan** [comment]
I downloaded the binary from https://github.com/bytedeco/javacv and extracted those files from ffmpeg-android-x86 and ffmpeg-android-arm (though I couldn't find any for different architectures).

**Comment by tspvivek** [comment]
@vanwafang Thanks for your precompiled libraries. It works great. Is it possible to compile to support only audio formats alone. So that the size of library is small, might help developers like me who needs only for playing audios and audio streams alone.

**Comment by vanwafang** [comment]
@tspvivek I used the same compile settings as used in this package https://github.com/wseemann/FFmpegMediaPlayer/blob/master/gradle/fmp-library/library/src/main/ffmpeg-2.5.3.tar.gz. Look for the FLAGS inside arm-build.sh, mips-build.sh, ...

**Comment by asakaplan** [comment]
Would someone be willing to post their gradle file to get this working?

**Comment by asakaplan** [comment]
Would someone be willing to post their gradle file to get this working? @vanwafang  @tspvivek

**Comment by branemk** [comment]
@vanwafang Thank you man, you are a genious . 

@asakaplan just copy and replace four folders from @vanwafang  in your project jniLabs folder .

**Comment by tspvivek** [comment]
@vanwafang  Thanks, I will try and let you know if i succeed.

**Comment by droidster** [comment]
@vanwafang That makes it a bit clearer. Thanks!

**Comment by adelinolobao** [comment]
Hi guys, I'm kinda struggling to use the precompiled libraries from @vanwafang. In my project I use the FFmpegMediaPlayer through a .jar prebuilt by @wseemann (fmp.jar, x86.jar, armeabi.jar ...) but if I replace the x86.jar armeabi.jar, armeabi-v7.jar and mips.jar by the jniLibs correspondent I get this error UnsatisfiedLinkError from libffmpeg_mediaplayer_so.jni which is strange because the system is able to load all the *.so libs (avcodec.so, avformat.so, ...) but not this one. Can someone help me here? Or at least share the all-fmp.aar result from your compiled project? Thanks in advance!

**Comment by wseemann** [comment]
I don't advise using binaries that someone else compiled. This is a security risk. I'm in the process of rewriting the library. Here is the first rewrite release, which solves this issue: https://github.com/wseemann/FFmpegMediaPlayer/releases/tag/v1.0.0

**Comment by adelinolobao** [comment]
@wseemann thank you for the quick response.

**Comment by laminsk** [comment]
@wseemann Thanks for the rewrite, looking forward to future updates.

**Comment by vanwafang** [comment]
@wseemann I did not use any other source code than provided within this project. I checked out the git project and used the compile scripts in ffmpeg.2.5.3.tar.gz using the latest NDK.

**Comment by wseemann** [comment]
I'm not accusing you of doing anything malicious, I sincerely appreciate
you chipping in while I was busy with other projects. I'm just trying to
raise the issue and educate people that using prebuilt binaries from an
unknown source isn't very advisable. It has nothing to do with you or your
integrity. Thanks again!

**Comment by NitroTek** [comment]
I build rewrite. Launch demo application and raise exception. Fatal signal 11.

**Comment by wseemann** [comment]
This should be fixed in version [1.0.1](https://github.com/wseemann/FFmpegMediaPlayer/releases/tag/v1.0.1).
